services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db_demo
    restart: unless-stopped
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5428:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: